[Icon Theme]
Name=Novo Project
Comment=Early work on the next KDE icon theme
Inherits=

Directories=actions/scalable,actions/small,apps/preferences,apps/scalable,apps/small,categories/scalable,categories/preferences,categories/small,mimetypes/scalable,places/scalable,places/small

[actions/scalable]
Size=22
Context=Actions
Type=Scalable
MinSize=22
MaxSize=24

[actions/small]
Size=16
Context=Actions
Type=Fixed

[apps/scalable]
Size=48
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

[apps/preferences]
Size=32
Context=Applications
Type=Fixed

[apps/small]
Size=16
Context=Applications
Type=Fixed

[categories/scalable]
Size=22
Context=Categories
Type=Scalable
MinSize=16
MaxSize=22

[categories/preferences]
Size=32
Context=Categories
Type=Fixed

[categories/small]
Size=16
Context=Categories
Type=Fixed

[mimetypes/scalable]
Size=54
Context=Places
Type=Scalable
MinSize=24
MaxSize=512

[places/scalable]
Size=64
Context=Places
Type=Scalable
MinSize=24
MaxSize=512

[places/small]
Size=16
Context=Places
Type=Scalable
MinSize=16
MaxSize=22