[Icon Theme]
Name=Novo Project
Comment=Early work on the next KDE icon theme
Inherits=

Directories=actions/scalable,actions/small,apps/scalable,categories/scalable,mimetypes/scalable,places/scalable,places/small

[actions/scalable]
Size=22
Context=Actions
Type=Scalable
MinSize=22
MaxSize=24

[actions/small]
Size=16
Context=Actions
Type=Fixed

[apps/scalable]
Size=64
Context=Applications
Type=Scalable
MinSize=64
MaxSize=512

[categories/scalable]
Size=22
Context=Categories
Type=Scalable
MinSize=16
MaxSize=22

[mimetypes/scalable]
Size=54
Context=Places
Type=Scalable
MinSize=24
MaxSize=512

[places/scalable]
Size=64
Context=Places
Type=Scalable
MinSize=24
MaxSize=512

[places/small]
Size=16
Context=Places
Type=Scalable
MinSize=16
MaxSize=22